# Generated by Django 6.0.4 on 2026-05-02 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0003_remove_thread_user_chatroom_chat_delete_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(null=True)),
                ('chatroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
            ],
            options={
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contract.contract')),
                ('location', models.CharField(max_length=40, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('month_rent', models.IntegerField(null=True)),
                ('deposit', models.IntegerField(null=True)),
                ('house_cost', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'property_info',
            },
        ),
    ]
