--
-- PostgreSQL database dump
--

\restrict MEKTvrWhS3DdcYNvZxN5PEi1LfYlKtSaLqslj28hCfmLF4QFEieZkwVEZednOch

-- Dumped from database version 18.3 (Homebrew)
-- Dumped by pg_dump version 18.3 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO aigo_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: aigo_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO aigo_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: aigo_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO aigo_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: aigo_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public.chat_message (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    role character varying(16) NOT NULL,
    content text NOT NULL,
    thread_id bigint NOT NULL
);


ALTER TABLE public.chat_message OWNER TO aigo_user;

--
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: aigo_user
--

ALTER TABLE public.chat_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_thread; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public.chat_thread (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title character varying(200) NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.chat_thread OWNER TO aigo_user;

--
-- Name: chat_thread_id_seq; Type: SEQUENCE; Schema: public; Owner: aigo_user
--

ALTER TABLE public.chat_thread ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_thread_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO aigo_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: aigo_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO aigo_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: aigo_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO aigo_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: aigo_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO aigo_user;

--
-- Name: email; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public.email (
    id uuid NOT NULL,
    email character varying(320) NOT NULL,
    code character varying(6) NOT NULL,
    purpose character varying(20) NOT NULL,
    is_verified boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL
);


ALTER TABLE public.email OWNER TO aigo_user;

--
-- Name: user; Type: TABLE; Schema: public; Owner: aigo_user
--

CREATE TABLE public."user" (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    user_id uuid NOT NULL,
    email character varying(320) NOT NULL,
    nickname character varying(6) NOT NULL,
    is_verified boolean NOT NULL,
    is_admin boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    update_at timestamp with time zone NOT NULL
);


ALTER TABLE public."user" OWNER TO aigo_user;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	7	add_user
22	Can change user	7	change_user
23	Can delete user	7	delete_user
24	Can view user	7	view_user
25	Can add email verification	6	add_emailverification
26	Can change email verification	6	change_emailverification
27	Can delete email verification	6	delete_emailverification
28	Can view email verification	6	view_emailverification
29	Can add thread	9	add_thread
30	Can change thread	9	change_thread
31	Can delete thread	9	delete_thread
32	Can view thread	9	view_thread
33	Can add message	8	add_message
34	Can change message	8	change_message
35	Can delete message	8	delete_message
36	Can view message	8	view_message
\.


--
-- Data for Name: chat_message; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public.chat_message (id, created_at, updated_at, role, content, thread_id) FROM stdin;
1	2026-05-01 01:47:10.752995+09	2026-05-01 01:47:10.753015+09	user	ㅁㄹㅇ	1
2	2026-05-01 01:47:15.190602+09	2026-05-01 01:47:15.190629+09	user	ㅁㄴㅇㄹ	1
3	2026-05-01 01:47:15.808865+09	2026-05-01 01:47:15.808879+09	user	ㅁㄴㅇㄹ	1
4	2026-05-01 01:47:16.252673+09	2026-05-01 01:47:16.252704+09	user	ㅁㄴㅇㄹ	1
5	2026-05-01 01:47:16.516857+09	2026-05-01 01:47:16.516878+09	user	ㅇㄹ	1
6	2026-05-01 01:47:16.767538+09	2026-05-01 01:47:16.767561+09	user	ㄹㅇ	1
7	2026-05-01 01:47:16.948451+09	2026-05-01 01:47:16.948467+09	user	ㄹ	1
8	2026-05-01 01:47:25.391196+09	2026-05-01 01:47:25.39122+09	user	ㅇㄹㅁ	4
9	2026-05-01 01:51:33.744817+09	2026-05-01 01:51:33.744859+09	user	애	5
10	2026-05-01 01:51:33.745964+09	2026-05-01 01:51:33.745983+09	user	응애	5
11	2026-05-01 01:51:35.746017+09	2026-05-01 01:51:35.746037+09	user	?	5
12	2026-05-01 01:51:38.04901+09	2026-05-01 01:51:38.049035+09	user	가	5
13	2026-05-01 01:51:38.049839+09	2026-05-01 01:51:38.049855+09	user	머야 왜 두개들어가	5
14	2026-05-01 01:51:39.675246+09	2026-05-01 01:51:39.675268+09	user	???	5
15	2026-05-01 01:51:41.678385+09	2026-05-01 01:51:41.678416+09	user	장난해?	5
16	2026-05-01 01:51:43.113647+09	2026-05-01 01:51:43.113674+09	user	야	5
17	2026-05-01 01:51:43.114619+09	2026-05-01 01:51:43.114644+09	user	야	5
18	2026-05-01 01:51:44.616502+09	2026-05-01 01:51:44.616518+09	user	오	5
19	2026-05-01 01:51:44.616986+09	2026-05-01 01:51:44.616995+09	user	오	5
20	2026-05-01 01:51:47.969134+09	2026-05-01 01:51:47.969162+09	user	자	5
21	2026-05-01 01:51:47.970032+09	2026-05-01 01:51:47.970052+09	user	한글자	5
22	2026-05-01 01:51:48.950812+09	2026-05-01 01:51:48.950838+09	user	오	5
23	2026-05-01 01:51:48.951808+09	2026-05-01 01:51:48.951827+09	user	오	5
24	2026-05-01 02:01:00.305936+09	2026-05-01 02:01:00.305957+09	user	똥쟁이 세형	1
25	2026-05-01 02:01:00.306984+09	2026-05-01 02:01:00.307006+09	user	형	1
\.


--
-- Data for Name: chat_thread; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public.chat_thread (id, created_at, updated_at, title, user_id) FROM stdin;
1	2026-05-01 01:47:10.665952+09	2026-05-01 01:47:10.66599+09		2b7dfe93-f040-49ff-8942-d4653f823592
2	2026-05-01 01:47:18.920099+09	2026-05-01 01:47:18.92013+09		2b7dfe93-f040-49ff-8942-d4653f823592
3	2026-05-01 01:47:19.439759+09	2026-05-01 01:47:19.439788+09		2b7dfe93-f040-49ff-8942-d4653f823592
4	2026-05-01 01:47:21.197376+09	2026-05-01 01:47:21.197401+09		2b7dfe93-f040-49ff-8942-d4653f823592
5	2026-05-01 01:47:21.808073+09	2026-05-01 01:47:21.808106+09		2b7dfe93-f040-49ff-8942-d4653f823592
6	2026-05-02 15:04:26.006989+09	2026-05-02 15:04:26.007045+09		2b7dfe93-f040-49ff-8942-d4653f823592
7	2026-05-02 15:04:27.402268+09	2026-05-02 15:04:27.4023+09		2b7dfe93-f040-49ff-8942-d4653f823592
8	2026-05-02 15:04:28.138157+09	2026-05-02 15:04:28.138183+09		2b7dfe93-f040-49ff-8942-d4653f823592
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	core	emailverification
7	core	user
8	chat	message
9	chat	thread
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	core	0001_initial	2026-05-01 01:08:40.773527+09
2	contenttypes	0001_initial	2026-05-01 01:08:40.780631+09
3	admin	0001_initial	2026-05-01 01:08:40.792855+09
4	admin	0002_logentry_remove_auto_add	2026-05-01 01:08:40.794154+09
5	admin	0003_logentry_add_action_flag_choices	2026-05-01 01:08:40.795298+09
6	contenttypes	0002_remove_content_type_name	2026-05-01 01:08:40.798815+09
7	auth	0001_initial	2026-05-01 01:08:40.819495+09
8	auth	0002_alter_permission_name_max_length	2026-05-01 01:08:40.822188+09
9	auth	0003_alter_user_email_max_length	2026-05-01 01:08:40.82436+09
10	auth	0004_alter_user_username_opts	2026-05-01 01:08:40.825854+09
11	auth	0005_alter_user_last_login_null	2026-05-01 01:08:40.827235+09
12	auth	0006_require_contenttypes_0002	2026-05-01 01:08:40.827696+09
13	auth	0007_alter_validators_add_error_messages	2026-05-01 01:08:40.828943+09
14	auth	0008_alter_user_username_max_length	2026-05-01 01:08:40.830373+09
15	auth	0009_alter_user_last_name_max_length	2026-05-01 01:08:40.831829+09
16	auth	0010_alter_group_name_max_length	2026-05-01 01:08:40.834904+09
17	auth	0011_update_proxy_permissions	2026-05-01 01:08:40.836984+09
18	auth	0012_alter_user_first_name_max_length	2026-05-01 01:08:40.838313+09
19	chat	0001_initial	2026-05-01 01:08:40.852282+09
20	sessions	0001_initial	2026-05-01 01:08:40.858153+09
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
48zqh42na1wj106enszsdvwx55ebkvk4	.eJxVjUsOgzAMBe-SdYmcxAHcZfc9A3LiuPQjkPisqt69ILFo12_mzdt0vC59t85l6u5izsanRrRQqBQQKiTVqiX0lWAdg7Y-RPLm9Kslzs8y7K48eLiNNo_DMt2T3RF7rLO9jlJel4P9O-h57jc7kXfFefAp5tBAarhk1S2LUrY2ckgOSEApkwq5COxCC5iUa-cims8XqX9AVA:1wIUkn:XPClUkUNHjR9QKIdNbd_n4fu4ubYOeaduPBjovHYcJo	2026-05-15 02:00:45.423303+09
\.


--
-- Data for Name: email; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public.email (id, email, code, purpose, is_verified, created_at, expires_at) FROM stdin;
4c20b47a-e8ec-41d1-aa86-4a1929150841	jsw000395@gmail.com	590327	SIGNUP	t	2026-05-01 01:45:49.239183+09	2026-05-01 01:48:49.238845+09
f1d803a1-98fc-4c73-a8b5-313a96cdd8de	jpaper.dev@gmail.com	659764	SIGNUP	t	2026-05-01 01:49:35.492293+09	2026-05-01 01:52:35.491987+09
d0abd9d1-cebd-4882-bb3f-7a3cb08b5eee	zaq1590@naver.com	471265	SIGNUP	t	2026-05-01 01:58:17.576697+09	2026-05-01 02:01:17.576156+09
663f5b66-36f1-4c34-93ac-d3191232ad4f	jinsam0509@naver.com	179328	SIGNUP	t	2026-05-01 01:59:36.147276+09	2026-05-01 02:02:36.14694+09
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: aigo_user
--

COPY public."user" (password, last_login, user_id, email, nickname, is_verified, is_admin, created_at, update_at) FROM stdin;
pbkdf2_sha256$1200000$leHaFZkV0BrgDV6yrEfw4E$z+BxYmlT1D2CxV4Uu/rfglZp365anUFAINaSOuGhcCg=	2026-05-02 15:06:50.85443+09	2b7dfe93-f040-49ff-8942-d4653f823592	jsw000395@gmail.com	잡기술연구원	t	f	2026-05-01 01:46:25.388565+09	2026-05-01 01:46:25.395228+09
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aigo_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aigo_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aigo_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- Name: chat_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aigo_user
--

SELECT pg_catalog.setval('public.chat_message_id_seq', 25, true);


--
-- Name: chat_thread_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aigo_user
--

SELECT pg_catalog.setval('public.chat_thread_id_seq', 5, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aigo_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aigo_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aigo_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- Name: chat_thread chat_thread_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.chat_thread
    ADD CONSTRAINT chat_thread_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: email email_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.email
    ADD CONSTRAINT email_pkey PRIMARY KEY (id);


--
-- Name: user user_email_key; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: chat_message_thread_id_6a43dfba; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX chat_message_thread_id_6a43dfba ON public.chat_message USING btree (thread_id);


--
-- Name: chat_thread_user_id_f117ffc8; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX chat_thread_user_id_f117ffc8 ON public.chat_thread USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: user_email_54dc62b2_like; Type: INDEX; Schema: public; Owner: aigo_user
--

CREATE INDEX user_email_54dc62b2_like ON public."user" USING btree (email varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_message chat_message_thread_id_6a43dfba_fk_chat_thread_id; Type: FK CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_thread_id_6a43dfba_fk_chat_thread_id FOREIGN KEY (thread_id) REFERENCES public.chat_thread(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_thread chat_thread_user_id_f117ffc8_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.chat_thread
    ADD CONSTRAINT chat_thread_user_id_f117ffc8_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: aigo_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict MEKTvrWhS3DdcYNvZxN5PEi1LfYlKtSaLqslj28hCfmLF4QFEieZkwVEZednOch

