# Generated by Django 6.0.4 on 2026-04-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='has_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_chat_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
